---
  config:
    class:
      hideEmptyMembersBox: true
  title: World Container Data Ownership (for Callbacks)
---
classDiagram
    OpenCommand <|-- WorldContainerVIew
    WorldContainerVIew <|-- WorldContainerViewFrameHandlers

    WorldContainerViewFrameHandlers <|-- ContainerChoiceFrameHandler
    WorldContainerViewFrameHandlers <|-- ContainerFrameHandler
    class OpenCommand{
      +Level
      +UI
      +TerminalManager
      +KeyInputResolver
    }

    class WorldContainerVIew{
      +UI
      +TerminalManager
      +WorldContainerViewFrameHandlers
      +Container
      +Callback
      +KeyInputResolver
    }

    class WorldContainerViewFrameHandlers {
        +Vec~ContainerFrameHandler~
        +Option~ContainerChoiceFrameHandler~
    }

    class ContainerChoiceFrameHandler {
      -choices: Vec~Container~,
      -columns : Vec~Column~,
      +item_list_selection : ItemListSelection,
    }
    class ContainerFrameHandler {
      +container : Container,
      -columns : Vec~Column~,
      -row_count: i32,
      +item_list_selection : ItemListSelection,
      -usage_line : UsageLine
    }
