name: Rust Build

on:
  push:
    branches: [ "master" ]
    paths:
      - 'arq/src/*'
  # PRs into master  
  pull_request:
    branches: [ "master" ]
    paths:
      - 'arq/src/*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      working-directory: ./arq
      run: cargo build --verbose
    - name: Run unit tests
      working-directory: ./arq
      run: cargo test --verbose
